### ISSUE TITLE
Unittest not found

### ISSUE THREAD

**Issue by erlebach** [mnoukhov/gradescope-autograder-template#1]
I am following instructions in the README.md file, which states: 
```
## running your tests locally
you can run all your tests in the assignment folder with `unittest`
```
cd assignment0
python -m unittest
```
You provide very detailed instructions, but the commands above don't work because unittest is not installed. In fact, it is not a part of the requirements file. Perhaps I am missing some instructions elsewhere? Of course, I know I can install `unittest`, but the idea is for me to follow your instructions since you want the system to work within Gradescope. I hope you are still listening. Thanks.
 
    Gordon

**Comment by erlebach** [comment]
I solved my problem by running requirements.txt (not sure I understand why unittest became available. )

**Comment by mnoukhov** [comment]
`unittest` is a python library that needs to be installed before it can be used. Since it was one of the libraries specified in `requirements.txt`, you installed it when you ran `pip install -r requirements.txt`.

**Comment by erlebach** [comment]
Got it. This now works.
