### ISSUE TITLE
deploy key in setup.sh

### ISSUE THREAD

**Issue by erlebach** [mnoukhov/gradescope-autograder-template#2]
Here is your template `setup.sh` (see below). You state to make sure to include your private key at a specific location in this file. Exactly what does this mean? The private key should not be moved anywhere and should stay on a local computer. This seems like a security risk to me.

     Gordon
     
```
#!/usr/bin/env bash

# make_assignment.sh will replace the lines below, DO NOT REMOVE
GITHUB_REPO=git@github.com:fsu-sc/gradescope_template.git
REPO_NAME=gradescope-template

cd /autograder/source

apt-get install -y python3 python3-pip python3-dev

mkdir -p /root/.ssh
cp ssh_config /root/.ssh/config
# Make sure to include your private key here
cp deploy_key /root/.ssh/deploy_key
chmod 400 /root/.ssh/deploy_key
# To prevent host key verification errors at runtime
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

# Clone autograder files
git clone $GITHUB_REPO /autograder/$REPO_NAME
# Install python dependencies
pip3 install -r /autograder/$REPO_NAME/requirements.txt
```

**Comment by mnoukhov** [comment]
To allow your gradescope code to `git pull` the latest code in your assignment repo, it needs to prove it has access to the repo, which requires either a private key, or safer, a [deploy key](https://docs.github.com/en/rest/deploy-keys/deploy-keys?apiVersion=2022-11-28). So your deploy key needs to be part of the files you upload to gradescope. 

But keeping your deploy key in your github repo is bad practice. So my solution is to copy the deploy key from your local machine directly into the assignment `.zip` when you create the repo. That way, your deploy key is never uploaded anywhere except to your gradescope code. You can also create the deploy key so it only grants pull access to the specific assignment repo you have, which should minimize any possible security issues.

Hope this clears things up!

**Comment by erlebach** [comment]
Thank you very much! Your reply does clear things up. Glad you are still listening!
